import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";

const credentials = process.env.AWS_ACCESS_KEY_ID && process.env.AWS_SECRET_ACCESS_KEY 
    ? {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
    }
    : undefined;

const sesClient = new SESClient({
    region: process.env.SES_REGION || process.env.AWS_REGION || "us-west-2",
    ...(credentials ? { credentials } : {})
});

let FROM_ADDRESS = process.env.SES_FROM_ADDRESS || "BasaltCRM <sysadm@basalthq.com>";
if ((FROM_ADDRESS.startsWith('"') && FROM_ADDRESS.endsWith('"')) || (FROM_ADDRESS.startsWith("'") && FROM_ADDRESS.endsWith("'"))) {
    FROM_ADDRESS = FROM_ADDRESS.substring(1, FROM_ADDRESS.length - 1);
}

export async function sendEmail(to: string, subject: string, htmlBody: string): Promise<{ success: boolean; error?: string }> {
    try {
        const command = new SendEmailCommand({
            Destination: { ToAddresses: [to] },
            Message: {
                Body: { Html: { Charset: "UTF-8", Data: htmlBody } },
                Subject: { Charset: "UTF-8", Data: subject }
            },
            Source: FROM_ADDRESS
        });

        const response = await sesClient.send(command);
        console.log(`Email sent to ${to}. Message ID:`, response.MessageId);
        return { success: true };
    } catch (error: any) {
        console.error(`Failed to send email to ${to}:`, error);
        return { success: false, error: error.message || String(error) };
    }
}

export async function sendPasswordResetEmail(to: string, token: string) {
    const fallbackUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://basalthq.com';
    const baseUrl = process.env.NEXTAUTH_URL || process.env.NEXT_PUBLIC_APP_URL || fallbackUrl;
    const resetUrl = `${baseUrl}/nexus/reset-password?token=${token}`;
    
    const subject = "Password Reset requested for Basalt Nexus";
    const body = `
        <div style="background-color: #050505; padding: 60px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #ffffff;">
            <div style="max-width: 500px; margin: 0 auto; background-color: #0A0A0A; border-radius: 16px; overflow: hidden; border: 1px solid #222;">
                <!-- Header -->
                <div style="text-align: center; padding: 40px 20px 20px; border-bottom: 1px solid #1a1a1a;">
                    <h1 style="color: #ffffff; font-size: 28px; font-weight: 800; margin: 0; letter-spacing: -0.5px;">BASALT<span style="color: #119dff;">HQ</span></h1>
                    <p style="color: #119dff; font-size: 12px; font-weight: 700; margin-top: 8px; margin-bottom: 0; text-transform: uppercase; letter-spacing: 3px;">Nexus Operations</p>
                </div>
                
                <!-- Body Content -->
                <div style="padding: 40px 30px;">
                    <h2 style="font-size: 20px; font-weight: 600; margin-top: 0; margin-bottom: 16px; color: #ffffff;">Reset your password</h2>
                    <p style="color: #a1a1aa; font-size: 15px; line-height: 1.6; margin-bottom: 32px;">
                        We received a request to reset the password for your Basalt Nexus account associated with <strong style="color: #eee;">${to}</strong>. You can securely configure a new password by clicking the button below.
                    </p>
                    
                    <div style="text-align: center; margin: 32px 0;">
                        <a href="${resetUrl}" style="display: inline-block; padding: 14px 36px; background-color: #119dff; color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: 600; font-size: 15px;">Reset Password</a>
                    </div>
                    
                    <p style="color: #71717a; font-size: 13px; line-height: 1.5; margin-bottom: 0;">
                        If you did not request this password reset, your account is perfectly safe. You can safely ignore this message. For security, this reset link will automatically expire in 2 hours.
                    </p>
                </div>
                
                <!-- Footer -->
                <div style="padding: 24px; text-align: center; background-color: #050505; border-top: 1px solid #1a1a1a;">
                    <p style="color: #52525b; font-size: 12px; margin: 0;">
                        Securely generated by the BasaltHQ Main Street Ontology Engine.<br/>
                        &copy; ${new Date().getFullYear()} BasaltHQ, Inc.
                    </p>
                </div>
            </div>
        </div>
    `;
    
    return sendEmail(to, subject, body);
}

export async function sendAccreditationUpdateEmail(to: string, status: string, notes?: string) {
    const subject = `Accreditation Review Update: ${status.toUpperCase()}`;
    
    const body = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2>Accreditation Review Status Update</h2>
            <p>Your accreditation status has been updated to: <strong>${status}</strong>.</p>
            ${notes ? `<p><strong>Administrator Notes:</strong> ${notes}</p>` : ''}
            <p>Please log in to your Basalt Nexus dashboard to view details and proceed.</p>
        </div>
    `;
    
    return sendEmail(to, subject, body);
}

export async function sendProposalNotificationEmail(to: string, title: string) {
    const subject = `New Governance Proposal: ${title}`;
    
    const body = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2>New Governance Proposal Requires Your Attention</h2>
            <p>A new proposal titled <strong>"${title}"</strong> has been published on the Cap Table and Governance module.</p>
            <p>Please visit the Basalt Nexus Cap Table dashboard to review the dilution impact and cast your vote.</p>
        </div>
    `;
    
    return sendEmail(to, subject, body);
}
